//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDFKeeper.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PDFKeeper.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel?.
        /// </summary>
        internal static string CancelQuestion {
            get {
                return ResourceManager.GetString("CancelQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author, Subject, Category, and Tax Year cannot all be blank!.
        /// </summary>
        internal static string CommonFieldsCannotAllBeBlank {
            get {
                return ResourceManager.GetString("CommonFieldsCannotAllBeBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Added cannot be blank!.
        /// </summary>
        internal static string DateAddedCannotBeBlank {
            get {
                return ResourceManager.GetString("DateAddedCannotBeBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Date_Time&gt;.
        /// </summary>
        internal static string DateTimeToken {
            get {
                return ResourceManager.GetString("DateTimeToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Date&gt;.
        /// </summary>
        internal static string DateToken {
            get {
                return ResourceManager.GetString("DateToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Exception has occurred..
        /// </summary>
        internal static string DefaultDatabaseExceptionMessage {
            get {
                return ResourceManager.GetString("DefaultDatabaseExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}. (Document ID {1}).
        /// </summary>
        internal static string DefaultDocumentException {
            get {
                return ResourceManager.GetString("DefaultDocumentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected documents?.
        /// </summary>
        internal static string DeleteSelectedDocuments {
            get {
                return ResourceManager.GetString("DeleteSelectedDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete {0} to the Recycle Bin?.
        /// </summary>
        internal static string DeleteToRecycleBin {
            get {
                return ResourceManager.GetString("DeleteToRecycleBin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.  Document ID {1} may have been deleted..
        /// </summary>
        internal static string DocumentMayHaveBeenDeletedException {
            get {
                return ResourceManager.GetString("DocumentMayHaveBeenDeletedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract all attachments from the PDF to a ZIP file?
        ///To extract to a folder, select No..
        /// </summary>
        internal static string ExtractAttachments {
            get {
                return ResourceManager.GetString("ExtractAttachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract all embedded files from the PDF to a ZIP file?
        ///To extract to a folder, select No..
        /// </summary>
        internal static string ExtractEmbeddedFiles {
            get {
                return ResourceManager.GetString("ExtractEmbeddedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} contains % and/or + in the filename which are invalid characters! Rename the file and try again..
        /// </summary>
        internal static string FileNameInvalid {
            get {
                return ResourceManager.GetString("FileNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;FileName&gt;.
        /// </summary>
        internal static string FileNameToken {
            get {
                return ResourceManager.GetString("FileNameToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more mandatory fields are blank!.
        /// </summary>
        internal static string MandatoryFieldsAreBlank {
            get {
                return ResourceManager.GetString("MandatoryFieldsAreBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name cannot be blank!.
        /// </summary>
        internal static string NameCannotBeBlank {
            get {
                return ResourceManager.GetString("NameCannotBeBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name contains one or more characters not allowed in file names!.
        /// </summary>
        internal static string NameContainsCharsNotAllowed {
            get {
                return ResourceManager.GetString("NameContainsCharsNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes for selected document have been modified.
        ///Do you want to save changes before closing?.
        /// </summary>
        internal static string NotesModified {
            get {
                return ResourceManager.GetString("NotesModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes size in bytes is {0} which is too large. Reduce the size to {1} or less and try saving again..
        /// </summary>
        internal static string NotesSizeTooLarge {
            get {
                return ResourceManager.GetString("NotesSizeTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One find function must be true!.
        /// </summary>
        internal static string OneFindFunctionMustBeTrue {
            get {
                return ResourceManager.GetString("OneFindFunctionMustBeTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than {0} documents have been selected. Only the PDF for each of the {0} selected documents will be opened..
        /// </summary>
        internal static string OpenCheckedDocumentsMaximumReached {
            get {
                return ResourceManager.GetString("OpenCheckedDocumentsMaximumReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The required Oracle ODP.NET is missing and needs to be installed.
        ///
        ///Please refer to the help file topic &quot;Installing Oracle ODP.NET&quot; in the &quot;Client Setup for Multi-User Database&quot; section for instructions.
        ///
        ///PDFKeeper will need to be restarted after completing the install of Oracle ODP.NET..
        /// </summary>
        internal static string OracleOdpNetMissing {
            get {
                return ResourceManager.GetString("OracleOdpNetMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF contains User password and is not supported..
        /// </summary>
        internal static string PdfContainsUserPassword {
            get {
                return ResourceManager.GetString("PdfContainsUserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF files|*.pdf.
        /// </summary>
        internal static string PdfFilter {
            get {
                return ResourceManager.GetString("PdfFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF is invalid..
        /// </summary>
        internal static string PdfInvalid {
            get {
                return ResourceManager.GetString("PdfInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF Owner password is incorrect..
        /// </summary>
        internal static string PdfOwnerPasswordIncorrect {
            get {
                return ResourceManager.GetString("PdfOwnerPasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF Owner password required..
        /// </summary>
        internal static string PdfOwnerPasswordRequired {
            get {
                return ResourceManager.GetString("PdfOwnerPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Term cannot be blank!.
        /// </summary>
        internal static string SearchTermCannotBeBlank {
            get {
                return ResourceManager.GetString("SearchTermCannotBeBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Term contains improper usage of query operators and/or characters!.
        /// </summary>
        internal static string SearchTermSyntaxIncorrect {
            get {
                return ResourceManager.GetString("SearchTermSyntaxIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the folder location where to burst the PDF for the selected document:
        ///PDF file names will be prefixed with: PDFKeeper&lt;ID&gt;_.
        /// </summary>
        internal static string SelectBurstFolder {
            get {
                return ResourceManager.GetString("SelectBurstFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the folder location where the export folder structure will be created:.
        /// </summary>
        internal static string SelectExportFolder {
            get {
                return ResourceManager.GetString("SelectExportFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the folder location where to extract all PDF attachments for the selected document:.
        /// </summary>
        internal static string SelectExtractFolder {
            get {
                return ResourceManager.GetString("SelectExtractFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text files|*.txt.
        /// </summary>
        internal static string TextFilter {
            get {
                return ResourceManager.GetString("TextFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The changes you made to the Notes text box cannot be saved and have been lost because another user has updated the Notes for the same record.
        ///
        ///The contents of the Notes text box prior to the attempted save operation have been copied to the Clipboard..
        /// </summary>
        internal static string UnableToSaveNotes {
            get {
                return ResourceManager.GetString("UnableToSaveNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Profile already exists!.
        /// </summary>
        internal static string UploadProfileExists {
            get {
                return ResourceManager.GetString("UploadProfileExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZIP files|*.zip.
        /// </summary>
        internal static string ZipFilter {
            get {
                return ResourceManager.GetString("ZipFilter", resourceCulture);
            }
        }
    }
}
