'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1008
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'This class was auto-generated by the StronglyTypedResourceBuilder
'class via a tool like ResGen or Visual Studio.
'To add or remove a member, edit your .ResX file then rerun ResGen
'with the /str option, or rebuild your VS project.
'''<summary>
'''  A strongly-typed resource class, for looking up localized strings, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class DirectUploadConfigurationForm_Strings
	
	Private Shared resourceMan As Global.System.Resources.ResourceManager
	
	Private Shared resourceCulture As Global.System.Globalization.CultureInfo
	
	<Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
	Friend Sub New()
		MyBase.New
	End Sub
	
	'''<summary>
	'''  Returns the cached ResourceManager instance used by this class.
	'''</summary>
	<Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
	Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
		Get
			If Object.ReferenceEquals(resourceMan, Nothing) Then
				Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("PdfKeeper.DirectUploadConfigurationForm.Strings", GetType(DirectUploadConfigurationForm_Strings).Assembly)
				resourceMan = temp
			End If
			Return resourceMan
		End Get
	End Property
	
	'''<summary>
	'''  Overrides the current thread's CurrentUICulture property for all
	'''  resource lookups using this strongly typed resource class.
	'''</summary>
	<Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
	Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
		Get
			Return resourceCulture
		End Get
		Set
			resourceCulture = value
		End Set
	End Property
	
	'''<summary>
	'''  Looks up a localized string similar to Database User name.
	'''</summary>
	Friend Shared ReadOnly Property AuthorDatabaseUserName() As String
		Get
			Return ResourceManager.GetString("AuthorDatabaseUserName", resourceCulture)
		End Get
	End Property
	
	'''<summary>
	'''  Looks up a localized string similar to Windows User name.
	'''</summary>
	Friend Shared ReadOnly Property AuthorWindowsUserName() As String
		Get
			Return ResourceManager.GetString("AuthorWindowsUserName", resourceCulture)
		End Get
	End Property
	
	'''<summary>
	'''  Looks up a localized string similar to Are you sure you want to discard all modifications?.
	'''</summary>
	Friend Shared ReadOnly Property CancelPrompt() As String
		Get
			Return ResourceManager.GetString("CancelPrompt", resourceCulture)
		End Get
	End Property
	
	'''<summary>
	'''  Looks up a localized string similar to {0} cannot be deleted because it contains PDF documents..
	'''</summary>
	Friend Shared ReadOnly Property CannotDeleteFolder() As String
		Get
			Return ResourceManager.GetString("CannotDeleteFolder", resourceCulture)
		End Get
	End Property
	
	'''<summary>
	'''  Looks up a localized string similar to Delete {0}?.
	'''</summary>
	Friend Shared ReadOnly Property DeleteFolder() As String
		Get
			Return ResourceManager.GetString("DeleteFolder", resourceCulture)
		End Get
	End Property
	
	'''<summary>
	'''  Looks up a localized string similar to {0} is already configured..
	'''</summary>
	Friend Shared ReadOnly Property FolderAlreadyConfigured() As String
		Get
			Return ResourceManager.GetString("FolderAlreadyConfigured", resourceCulture)
		End Get
	End Property
	
	'''<summary>
	'''  Looks up a localized string similar to Folder name contains invalid characters..
	'''</summary>
	Friend Shared ReadOnly Property FolderNameInvalid() As String
		Get
			Return ResourceManager.GetString("FolderNameInvalid", resourceCulture)
		End Get
	End Property
	
	'''<summary>
	'''  Looks up a localized string similar to Scanned Document.
	'''</summary>
	Friend Shared ReadOnly Property SubjectScannedDocument() As String
		Get
			Return ResourceManager.GetString("SubjectScannedDocument", resourceCulture)
		End Get
	End Property
	
	'''<summary>
	'''  Looks up a localized string similar to Date.
	'''</summary>
	Friend Shared ReadOnly Property TitleDate() As String
		Get
			Return ResourceManager.GetString("TitleDate", resourceCulture)
		End Get
	End Property
	
	'''<summary>
	'''  Looks up a localized string similar to Date and Time.
	'''</summary>
	Friend Shared ReadOnly Property TitleDateTime() As String
		Get
			Return ResourceManager.GetString("TitleDateTime", resourceCulture)
		End Get
	End Property
	
	'''<summary>
	'''  Looks up a localized string similar to File name.
	'''</summary>
	Friend Shared ReadOnly Property TitleFileName() As String
		Get
			Return ResourceManager.GetString("TitleFileName", resourceCulture)
		End Get
	End Property
End Class
