'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5456
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'This class was auto-generated by the StronglyTypedResourceBuilder
'class via a tool like ResGen or Visual Studio.
'To add or remove a member, edit your .ResX file then rerun ResGen
'with the /str option, or rebuild your VS project.
'''<summary>
'''  A strongly-typed resource class, for looking up localized strings, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class MainForm_Strings
	
	Private Shared resourceMan As Global.System.Resources.ResourceManager
	
	Private Shared resourceCulture As Global.System.Globalization.CultureInfo
	
	<Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
	Friend Sub New()
		MyBase.New
	End Sub
	
	'''<summary>
	'''  Returns the cached ResourceManager instance used by this class.
	'''</summary>
	<Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
	Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
		Get
			If Object.ReferenceEquals(resourceMan, Nothing) Then
				Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("PdfKeeper.Client.MainForm.Strings", GetType(MainForm_Strings).Assembly)
				resourceMan = temp
			End If
			Return resourceMan
		End Get
	End Property
	
	'''<summary>
	'''  Overrides the current thread's CurrentUICulture property for all
	'''  resource lookups using this strongly typed resource class.
	'''</summary>
	<Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
	Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
		Get
			Return resourceCulture
		End Get
		Set
			resourceCulture = value
		End Set
	End Property
	
	'''<summary>
	'''  Looks up a localized string similar to Checking for a newer version of PDFKeeper....
	'''</summary>
	Friend Shared ReadOnly Property CheckingVersion() As String
		Get
			Return ResourceManager.GetString("CheckingVersion", resourceCulture)
		End Get
	End Property
	
	'''<summary>
	'''  Looks up a localized string similar to The PDF Document Upload folder watcher must be configured before it can be enabled.  Do you wish to configure the PDF Document Upload folder watcher?.
	'''</summary>
	Friend Shared ReadOnly Property ConfigureUploadWatcher() As String
		Get
			Return ResourceManager.GetString("ConfigureUploadWatcher", resourceCulture)
		End Get
	End Property
	
	'''<summary>
	'''  Looks up a localized string similar to Do you want to delete {0} after being uploaded?
	'''
	'''Note, having PDFKeeper delete the file after uploading is not recommended unless you have a backup or can easily reproduce the file..
	'''</summary>
	Friend Shared ReadOnly Property DeleteAfterUploading() As String
		Get
			Return ResourceManager.GetString("DeleteAfterUploading", resourceCulture)
		End Get
	End Property
	
	'''<summary>
	'''  Looks up a localized string similar to Delete all checked documents?.
	'''</summary>
	Friend Shared ReadOnly Property DeleteChecked() As String
		Get
			Return ResourceManager.GetString("DeleteChecked", resourceCulture)
		End Get
	End Property
	
	'''<summary>
	'''  Looks up a localized string similar to The Document Notes text box contains unsaved data.  Do you want to save changes?.
	'''</summary>
	Friend Shared ReadOnly Property DocumentNotesSavePrompt() As String
		Get
			Return ResourceManager.GetString("DocumentNotesSavePrompt", resourceCulture)
		End Get
	End Property
	
	'''<summary>
	'''  Looks up a localized string similar to Enable the Information Properties Editor folder watcher?.
	'''</summary>
	Friend Shared ReadOnly Property EnableFolderWatcherInfoPropEditor() As String
		Get
			Return ResourceManager.GetString("EnableFolderWatcherInfoPropEditor", resourceCulture)
		End Get
	End Property
	
	'''<summary>
	'''  Looks up a localized string similar to Enable the PDF Document Upload folder watcher?.
	'''</summary>
	Friend Shared ReadOnly Property EnableFolderWatcherUpload() As String
		Get
			Return ResourceManager.GetString("EnableFolderWatcherUpload", resourceCulture)
		End Get
	End Property
	
	'''<summary>
	'''  Looks up a localized string similar to End of error event.
	'''</summary>
	Friend Shared ReadOnly Property EndErrorEvent() As String
		Get
			Return ResourceManager.GetString("EndErrorEvent", resourceCulture)
		End Get
	End Property
	
	'''<summary>
	'''  Looks up a localized string similar to Information Properties Editor folder watcher.
	'''</summary>
	Friend Shared ReadOnly Property FolderWatcherInfoPropEditor() As String
		Get
			Return ResourceManager.GetString("FolderWatcherInfoPropEditor", resourceCulture)
		End Get
	End Property
	
	'''<summary>
	'''  Looks up a localized string similar to PDF Document Upload folder watcher.
	'''</summary>
	Friend Shared ReadOnly Property FolderWatcherUpload() As String
		Get
			Return ResourceManager.GetString("FolderWatcherUpload", resourceCulture)
		End Get
	End Property
	
	'''<summary>
	'''  Looks up a localized string similar to PDFKeeper Help.
	'''</summary>
	Friend Shared ReadOnly Property HelpTitle() As String
		Get
			Return ResourceManager.GetString("HelpTitle", resourceCulture)
		End Get
	End Property
	
	'''<summary>
	'''  Looks up a localized string similar to Improper use of operators and/or characters. For more information, please consult the User Guide..
	'''</summary>
	Friend Shared ReadOnly Property ImproperUsage() As String
		Get
			Return ResourceManager.GetString("ImproperUsage", resourceCulture)
		End Get
	End Property
	
	'''<summary>
	'''  Looks up a localized string similar to Information Properties Editor.
	'''</summary>
	Friend Shared ReadOnly Property InfoPropEditor() As String
		Get
			Return ResourceManager.GetString("InfoPropEditor", resourceCulture)
		End Get
	End Property
	
	'''<summary>
	'''  Looks up a localized string similar to {0} document(s) found..
	'''</summary>
	Friend Shared ReadOnly Property ListViewCount() As String
		Get
			Return ResourceManager.GetString("ListViewCount", resourceCulture)
		End Get
	End Property
	
	'''<summary>
	'''  Looks up a localized string similar to A newer version of PDFKeeper is available.
	'''</summary>
	Friend Shared ReadOnly Property NewerVersionAvailable() As String
		Get
			Return ResourceManager.GetString("NewerVersionAvailable", resourceCulture)
		End Get
	End Property
	
	'''<summary>
	'''  Looks up a localized string similar to {0} contains PDF documents that can be processed by the {1}.
	'''
	'''Is it okay to process these files?.
	'''</summary>
	Friend Shared ReadOnly Property OkayToProcessFiles() As String
		Get
			Return ResourceManager.GetString("OkayToProcessFiles", resourceCulture)
		End Get
	End Property
	
	'''<summary>
	'''  Looks up a localized string similar to Select PDF File(s) to Edit.
	'''</summary>
	Friend Shared ReadOnly Property OpenFileDialogTitleEdit() As String
		Get
			Return ResourceManager.GetString("OpenFileDialogTitleEdit", resourceCulture)
		End Get
	End Property
	
	'''<summary>
	'''  Looks up a localized string similar to Select PDF File(s) to Upload.
	'''</summary>
	Friend Shared ReadOnly Property OpenFileDialogTitleUpload() As String
		Get
			Return ResourceManager.GetString("OpenFileDialogTitleUpload", resourceCulture)
		End Get
	End Property
	
	'''<summary>
	'''  Looks up a localized string similar to [PDF deleted].
	'''</summary>
	Friend Shared ReadOnly Property PdfDeleted() As String
		Get
			Return ResourceManager.GetString("PdfDeleted", resourceCulture)
		End Get
	End Property
	
	'''<summary>
	'''  Looks up a localized string similar to PDF Document Upload.
	'''</summary>
	Friend Shared ReadOnly Property PdfDocUpload() As String
		Get
			Return ResourceManager.GetString("PdfDocUpload", resourceCulture)
		End Get
	End Property
	
	'''<summary>
	'''  Looks up a localized string similar to [PDF failed to delete].
	'''</summary>
	Friend Shared ReadOnly Property PdfFailedDelete() As String
		Get
			Return ResourceManager.GetString("PdfFailedDelete", resourceCulture)
		End Get
	End Property
	
	'''<summary>
	'''  Looks up a localized string similar to [PDF not deleted].
	'''</summary>
	Friend Shared ReadOnly Property PdfNotDeleted() As String
		Get
			Return ResourceManager.GetString("PdfNotDeleted", resourceCulture)
		End Get
	End Property
	
	'''<summary>
	'''  Looks up a localized string similar to {0} has been saved..
	'''</summary>
	Friend Shared ReadOnly Property PdfSaved() As String
		Get
			Return ResourceManager.GetString("PdfSaved", resourceCulture)
		End Get
	End Property
	
	'''<summary>
	'''  Looks up a localized string similar to Database does not support the use of * as a wildcard character! Use % instead.  For more information, please consult the User Guide..
	'''</summary>
	Friend Shared ReadOnly Property SearchTextUsageError() As String
		Get
			Return ResourceManager.GetString("SearchTextUsageError", resourceCulture)
		End Get
	End Property
	
	'''<summary>
	'''  Looks up a localized string similar to Select the folder to be watched that will call the Information Properties Editor:.
	'''</summary>
	Friend Shared ReadOnly Property SelectWatchedFolderInfoPropEditor() As String
		Get
			Return ResourceManager.GetString("SelectWatchedFolderInfoPropEditor", resourceCulture)
		End Get
	End Property
	
	'''<summary>
	'''  Looks up a localized string similar to Select the folder to be watched that will call the PDF Document Upload:.
	'''</summary>
	Friend Shared ReadOnly Property SelectWatchedFolderUpload() As String
		Get
			Return ResourceManager.GetString("SelectWatchedFolderUpload", resourceCulture)
		End Get
	End Property
	
	'''<summary>
	'''  Looks up a localized string similar to Start of error event.
	'''</summary>
	Friend Shared ReadOnly Property StartErrorEvent() As String
		Get
			Return ResourceManager.GetString("StartErrorEvent", resourceCulture)
		End Get
	End Property
	
	'''<summary>
	'''  Looks up a localized string similar to Unable to enable folder watcher.
	'''
	'''Reason: {0} cannot be a watched folder..
	'''</summary>
	Friend Shared ReadOnly Property UnableEnableFolderWatcher1() As String
		Get
			Return ResourceManager.GetString("UnableEnableFolderWatcher1", resourceCulture)
		End Get
	End Property
	
	'''<summary>
	'''  Looks up a localized string similar to Unable to enable folder watcher.
	'''
	'''Reason: the Information Properties Editor and Upload folder watchers cannot watch the same folder..
	'''</summary>
	Friend Shared ReadOnly Property UnableEnableFolderWatcher2() As String
		Get
			Return ResourceManager.GetString("UnableEnableFolderWatcher2", resourceCulture)
		End Get
	End Property
	
	'''<summary>
	'''  Looks up a localized string similar to Uploaded {0} document(s), skipped {1} document(s)..
	'''</summary>
	Friend Shared ReadOnly Property UploadedResult() As String
		Get
			Return ResourceManager.GetString("UploadedResult", resourceCulture)
		End Get
	End Property
	
	'''<summary>
	'''  Looks up a localized string similar to Uploading... ({0} of {1}).
	'''</summary>
	Friend Shared ReadOnly Property UploadingCounter() As String
		Get
			Return ResourceManager.GetString("UploadingCounter", resourceCulture)
		End Get
	End Property
End Class
